- name: ACCEPT TCP SSH traffic from bastion hosts
  iptables:
    chain: "INPUT"
    # eth1 is the default internal interface for DO droplets
    source: "{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}"
    protocol: "tcp"
    destination_port: 22
    jump: "ACCEPT"
  with_inventory_hostnames:
    - bastion

- name: ACCEPT TCP tinc traffic for known hosts
  iptables:
    chain: "INPUT"
    # eth1 is the default internal interface for DO droplets
    source: "{{ hostvars[item]['ansible_tun0']['ipv4']['address'] }}"
    protocol: "tcp"
    destination_port: 655
    jump: "ACCEPT"
  with_inventory_hostnames:
    - digitalocean

- name: ACCEPT UDP tinc traffic for known hosts
  iptables:
    chain: "INPUT"
    # eth1 is the default internal interface for DO droplets
    source: "{{ hostvars[item]['ansible_tun0']['ipv4']['address'] }}"
    protocol: "udp"
    destination_port: 655
    jump: "ACCEPT"
  with_inventory_hostnames:
    - digitalocean

- name: DROP all other inbound traffic on eth0
  iptables:
    chain: "INPUT"
    in_interface: "eth0"
    jump: "DROP"

- name: DROP all other inbound traffic on eth1
  iptables:
    chain: "INPUT"
    in_interface: "eth1"
    jump: "DROP"